# Pertemuan 3 - Desain dan Analisis Algoritma
---
`Nama:` Muhammad Satrio

`NIM:` 2022071059

## Lists

In [ ]:
# List merupakan salah satu tipe data yang dapat diubah dan mempunyai index

bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
print(bin_colors[1]) # Green

# [ ---- Slicing  ---- ]

print(bin_colors[0:3]) # ['Red', 'Green']
print(bin_colors[:3]) # ['Red', 'Green', 'Blue']
print(bin_colors[::1]) # ['Red', 'Green', 'Blue', 'Yellow']

print(bin_colors[2:0:-1]) # ['Blue', 'Green']

for i in bin_colors:
    print(i, "Square")
    """
    Ouput:
        Red Square
        Green Square
        Blue Square
        Yellow Square
    """

## Tuples

In [ ]:
# Tuples merupakan salah satu tipe data yang memiliki index, sama seperti lists tetapi tidak bisa diubah elementnya.

bin_colors = ('Red', 'Green','Blue','Yellow')
print(bin_colors[1]) # Green
print(bin_colors[2:]) # ('Blue', 'Yellow')

hariAwal = ("senin","selasa","rabu")
hariAkhir = ("kamis","jumat","sabtu")

hari = (hariAwal, hariAkhir)
print(hari) # (('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))

# Tuples dapat berisi berbagai macam tipe data
acak = (True, {'name' : 'depotkode','status': 'alive'}, [1,2,3])
print(acak) # (True, {'name': 'depotkode', 'status': 'alive'}, [1, 2, 3])

## Dictionary

In [ ]:
# Berbeda dengan tuples dan lists, tipe data dictionary mempunyai key dan value. Selain itu, key di dalam dictionary tidak boleh duplicate.

bin_colors = {
  "manual_color": "Yellow",
  "approved_color": "Green",
  "refused_color": "Red"
}

print(bin_colors) # {'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}

print(bin_colors.get("manual_color")) # Yellow

bin_colors["approved_color"] = "Purple"
print(bin_colors) # {'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}

## Sets

In [ ]:
# Tipe data sets digunakan untuk menyimpan berbagai macam item dalam satu variable. Element di dalamnya tidak dapat diubah tetapi bisa ditambah dan dihapus, tidak boleh duplicate, dan tidak teratur sehingga tipe data ini tidak memiliki index.

green = {'grass', 'leaves'}
print(green) # {'leaves', 'grass'}

# list menjadi set
set_01 = set([1, 2, 3, 4])
print(type(set_01)) # <class 'set'>
print(set_01) # {1, 2, 3, 4}

set_01.add(0)
print(set_01) # {0, 1, 2, 3, 4}
set_01.discard(1)
print(set_01) # {0, 2, 3, 4}

# Union Set
set_A = {1,2,3,4}
set_B = {3,4,5,6}

print(set_A|set_B) # {1, 2, 3, 4, 5, 6}
print(set_A.union(set_B)) # {1, 2, 3, 4, 5, 6}

# Intersection Set
print(set_A & set_B) # {3, 4}
print(set_A.intersection(set_B)) # {3, 4}

# Difference Set
# A - B
print(set_A - set_B) # {1, 2}
print(set_A.difference(set_B)) # {1, 2}

# B - A
print(set_B - set_A) # {5, 6}
print(set_B.difference(set_A)) # {5, 6}

# Symmetric Difference
print(set_A ^ set_B) # {1, 2, 5, 6}
print(set_A.symmetric_difference(set_B)) # {1, 2, 5, 6}



## DataFrames

In [58]:
# DataFrame adalah struktur data yang digunakan untuk menyimpan data tabular yang tersedia dalam paket pandas Python

import pandas as pd

df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]],
)

df.columns = ['id', 'name', 'age', 'decision']
print(df)
"""
Output:

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True
"""

print(df[['name', 'age']])
"""
Output:

     name  age
0   Fares   32
1   Elena   23
2  Steven   40
"""

print(df.iloc[:,3])
"""
Output:
0     True
1    False
2     True
"""

print(df[df.age>30])
"""
Output:
  id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True
"""

"""
Output
satu 	dua 	tiga
a 	1 	2 	3
b 	1 	2 	3
c 	1 	2 	3
d 	1 	2 	3
e 	1 	2 	3
"""
data = {'satu': [1,1,1,1,1],
        'dua' : [2,2,2,2,2],
        'tiga': [3,3,3,3,3]}

df = pd.DataFrame(data, index=['a','b','c','d','e'])

df.head()


satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

## Matrix

In [ ]:
# Matriks adalah struktur data dua dimensi dengan jumlah kolom dan baris yang tetap.

import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)
"""
Output:

[[11 12 13]
 [21 22 23]
 [31 32 33]]
"""
print(type(myMatrix)) # <class 'numpy.ndarray'>

# Transpose matrix
matriksC = np.array([[1,2,3],
		                [4,5,6]])
print("Matriks C : ")
print(matriksC)

transpose_matriks = np.transpose(matriksC)

print("Tranpose Matriks C : ")
print(transpose_matriks)

"""
Output:

Matriks C :
[[1 2 3]
 [4 5 6]]
Tranpose Matriks C :
[[1 4]
 [2 5]
 [3 6]]
"""

## Abstrak


In [ ]:
# Tipe data abstrak (ADT) adalah spesifikasi tipe data dalam suatu bahasa, yang tidak bergantung pada implementasi.

# Vector

myVector = [22, 33, 44, 55]
print(myVector) # [22, 33, 44, 55]
print(type(myVector)) # <class 'list'>

myVector = np.array([22,33,44,55])
print(myVector) # [22 33 44 55]
print(type(myVector)) # <class 'numpy.ndarray'>

# Stack
# Merupakan struktur data linier untuk menyimpan daftar satu dimensi. Itu dapat menyimpan item baik dengan cara Last-In, First-Out (LIFO) atau First-In, Last-Out (FILO).
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    return self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items) - 1]
  def size(self):
    return len(self.items)

stack = Stack()
stack.push("First")
stack.push("Second")
stack.push("Third")
stack.push("Fourth")

stack.isEmpty() # False
stack.peek() # Fourth
stack.size() # 4

# Queue
# Seperti stack, antrian menyimpan n elemen dalam struktur satu dimensi. Elemen ditambahkan dan dihapus dalam format FIFO.

class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    return self.items.insert(0, item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

queue = Queue()
queue.enqueue("Red")
queue.enqueue("Blue")
queue.enqueue("Green")
queue.enqueue("Yellow")

queue.isEmpty() # False
queue.size() # 4

# Tree
# Setiap tree memiliki kumpulan node yang terbatas sehingga memiliki elemen data awal yang disebut root dan kumpulan node yang disatukan oleh tautan yang disebut branch.

# Pohon Faktor
def prime_number(x):
    prime = []
    for i in range(1, x+1):
        count = 0
        if i == 1:
            continue
        for j in range(1, x+1):
            if i % j == 0:
                count += 1
        if count == 2:
            prime.append(i)
    return prime


def prime_factor(x):
    faktor = {}

    for i in prime_numbers:
        count = 0
        while x % i == 0:
            x /= i
            count += 1
            faktor[i] = count
    return faktor

prime_numbers = prime_number(120)
print(prime_factor(120))
"""
Output:

{2: 3, 3: 1, 5: 1}
Pohon Faktor dari 120 adalah 2^3, 3^1, 5^1
"""

"""
Output:
{2: 3, 3: 1, 5: 1}

"""

# Binary Tree
class Node:
    def __init__(self,data):
        self.left = None
        self.right = None
        self.data = data
    def PrintTree(self):
        if self.left:
            self.left.PrintTree()
        print(self.data),
        if self.right:
            self.right.PrintTree()

root = Node(2) # root
root.left = Node(3) # child kiri dari root
root.right = Node(5) # child kanan dari root
root.left.left = Node(7) # child kiri dari 3
root.left.right = Node(9) # child kanan dari 3
root.right.left = Node(11) # child kiri dari 5
root.right.right = Node(13) # child kanan dari 5
root.PrintTree()

## Latihan

In [ ]:
# No 1
# TODO: Buatlah list dengan nama "Mahasiswa" yang berisi nama, NIM, prodi, mata kuliah, tanggal hari ini, nama universitas. Tampilkan pada cell

from datetime import datetime
date = datetime.now()
date_fomat = "%d/%m/%Y"

Mahasiswa = ["Muhammad Satrio", "2022071059", "Informatika", "Desain dan Analisis Algoritma", date.strftime(date_fomat), "Universitas Pembangunan Jaya"]

print(Mahasiswa) # ['Muhammad Satrio', '2022071059', 'Informatika', 'Desain dan Analisis Algoritma', '13/09/2023', 'Universitas Pembangunan Jaya']

In [ ]:
# No 2
# TODO: Cetak NIM masing-masing dengan memanggil urutan indeks dalam list “Mahasiswa”!

print(Mahasiswa[1]) # 2022071059

In [ ]:
# No 3
# TODO: Cetak nama universitas dengan memanggil urutan indeks dalam list “Mahasiswa”!​

print(Mahasiswa[5]) # Universitas Pembangunan Jaya

In [ ]:
# No 4
# TODO: Cetak NIM dan Prodi menggunakan slicing!​

print(Mahasiswa[1:3]) # ['2022071059', 'Informatika']

In [ ]:
# No 5
# TODO: Cetak isi list “Mahasiswa”, tambahkan kata “UPJ” di depan!​

Mahasiswa.insert(0, "UPJ")
print(Mahasiswa) # ['UPJ', 'Muhammad Satrio', '2022071059', 'Informatika', 'Desain dan Analisis Algoritma', '13/09/2023', 'Universitas Pembangunan Jaya']

In [ ]:
# No 6
# TODO: Susun Tuple bernama “UPJ”,  isi dengan Universitas, Pembangunan, Jaya​

UPJ = ("Universitas", "Pembangunan", "Jaya")
print(UPJ)

In [ ]:
# No 7
"""
TODO:
    Buat  tuple bersarang bernama “nested_tuple” dengan nilai :
        Pertama = 100
        Kedua = 200, 400, 600
        Ketiga = 300
        Keempat = 400, 800
"""

Pertama = (100, )
Kedua = (200, 400, 600)
Ketiga = (300, )
Keempat = (400, 800)

nested_tuple = (Pertama, Kedua, Ketiga, Keempat)
print(nested_tuple) # ((100,), (200, 400, 600), (300,), (400, 800))

In [ ]:
# No 8
# TODO: Membuat dictionary Mahasiswa dengan key "Nama", "NIM", "Prodi", "Universitas"

Mahasiswa = {
    "Nama": "Muhammad Satrio",
    "NIM": "2022071059",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}

print(Mahasiswa) # {'Nama': 'Muhammad Satrio', 'NIM': '2022071059', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}

In [ ]:
# No 9
"""
TODO:
  Bagaimana menyusun red sehingga mendapatkan hasil berikut?
  >>> yellow|red
  {'dandelions', 'fire hydrant', 'blood', 'rose', 'leaves'}
  >>> yellow&red
  {‘leaves’,'fire hydrant'}
"""

yellow = {'rose', 'blood', 'leaves', 'fire hydrant'}
red = {'dandelions', 'leaves', 'fire hydrant'}

print(yellow|red) # {'dandelions', 'blood', 'leaves', 'fire hydrant', 'rose'}
print(yellow&red) # {'leaves', 'fire hydrant'}

In [23]:
# No 10

data = {
    "Prodi": ["Informatika", "Sistem Informasi", "Teknik Sipil"],
    "Mahasiswa": [50, 55, 40],
    "Laki-laki": [30, 30, 30],
    "Perempuan": [20, 25, 10]
}
df = pd.DataFrame(data, index=[1, 2, 3])
df.index.name = "No"
df.head()

Prodi  Mahasiswa  Laki-laki  Perempuan
No                                                   
1        Informatika         50         30         20
2   Sistem Informasi         55         30         25
3       Teknik Sipil         40         30         10

In [ ]:
# No 11
"""
TODO:

  Buatlah Matrix dengan nilai berikut
      [[ 100  200  300]
  [700  600  500]
  [900  1000  800 ]]
  Lakukan transpose matrix!
"""

matrix = np.array([
                   [100, 200, 300],
                   [700, 600, 500],
                   [900, 1000, 800]
                  ])
print("Sebelum Transpose: ")
print(matrix)

matrix_tp = np.transpose(matrix)

print("Setelah Transpose: ")
print(matrix_tp)

"""
Output:

Sebelum Transpose:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Setelah Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
"""